# Generated by Django 4.2.25 on 2025-10-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuponPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasarelaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuponPagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cupones.cuota')),
                ('cupon_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupones.cuponpago')),
            ],
            options={
                'unique_together': {('cupon_pago', 'cuota')},
            },
        ),
        migrations.AddField(
            model_name='cuponpago',
            name='cuotas_incluidas',
            field=models.ManyToManyField(related_name='cupones', through='cupones.CuponPagoCuota', to='cupones.cuota'),
        ),
        migrations.AddField(
            model_name='cuponpago',
            name='estado_cupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupones', to='cupones.estadocupon'),
        ),
        migrations.AddField(
            model_name='cuponpago',
            name='pasarela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupones', to='cupones.pasarelapago'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='estado_cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cupones.estadocuota'),
        ),
    ]
