# Generated by Django 4.2.25 on 2025-10-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponpago',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
